---
- hosts: homenet
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: Update packages
      yum: update_cache=yes

    - name: "Install Zabbix-Agent"
      apt: name={{ item }} state=present
      with_items:
        - zabbix-agent

    - name: "Turn on Zabbix-Agent and set them to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - zabbix-agent
